version: '3.8'
services:
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=siwon7096!
    volumes:
      - mysql_data:/var/lib/mysql
  
  mysql2:
    image: mysql:latest
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=siwon7096!
    volumes:
      - mysql2_data:/var/lib/mysql
  mysql3:
    image: mysql:latest
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=siwon7096!
    volumes:
      - mysql3_data:/var/lib/mysql
  redis:
    image: redis:latest
    ports:
      - 26379:6379

  my-spring-app:
    image: my-spring-app
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - redis

  my-spring-app2:
    image: my-spring-app2
    ports:
      - 8081:8080
    depends_on:
      - mysql2
      - redis

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    depends_on:
      - redis
      - mysql

volumes:
  mysql_data:
  mysql2_data:
  mysql3_data:
